### PR TITLE
Tracks memory pool stats (eden, survivor, tenured, etc.)

### PR DESCRIPTION
**Pull request by bdarfler**
This, along with https://github.com/etsy/statsd-jvm-profiler/pull/18 closes https://github.com/etsy/statsd-jvm-profiler/issues/17

### CODE REVIEW

**Comment by bdarfler** [comment]
Question about this. There is also a type field to denote on/off heap. I wasn't sure how to best add that to the metric name. Ideally you could graph all heap pools together on one graph.

**Comment by ajsquared** [comment]
What do you think of having the metrics like heap.total, heap.eden, etc and group them that way?

Doing this would require some changes to the dashboard, but that should be pretty straightforward.

**Comment by bdarfler** [comment]
Additionally I believe there might be spaces in the pool names. Is it best to replace them with a hyphen?

**Comment by ajsquared** [comment]
Yeah, replacing the spaces with hyphens is good.

**Comment by bdarfler** [comment]
Ah so you mean like:

`heap.total.{init, used, committed, max}`
`heap.eden.{init, used, committed, max}`

I like that.

**Comment by ajsquared** [comment]
Yeah, those metric names look good.

**Comment by bdarfler** [comment]
Ok I updated the metric names and I took a crack at fixing the visualizer. Let me know if I missed anything.

**Comment by ajsquared** [comment]
Looks great, thanks again for this!

**Pull request merged**
