### PR TITLE
Added support for https connection to InfluxDB

### PR DESCRIPTION
**Pull request by NoamShaish**

### CODE REVIEW

**Comment by NoamShaish** [comment]
@ajsquared I added support to https connection to influxDB, but for some reason the TravisCI fails on the java version feature. could you please assist?

**Comment by dossett** [comment]
@NoamShaish I updated the travis config and am rerunning the test for your PR.

**Comment by dossett** [comment]
Test passed, I'll try to give it a substantive review this week or next @NoamShaish , thanks for the contribution!

**Comment by NoamShaish** [comment]
@dossett any updates?

**Comment by dossett** [comment]
Thanks very much @NoamShaish !

**Pull request merged**
